"""Initial migration

Revision ID: 20251121_01
Revises: 
Create Date: 2025-11-21 08:18:22.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251121_01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('current_state', sa.String(length=64), server_default='init', nullable=False),
    sa.Column('is_transferred', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('handover_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', name='uq_calls_call_id')
    )
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=False)
    op.create_index(op.f('ix_calls_client_id'), 'calls', ['client_id'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_call_id'), 'call_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_client_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###

